controller_manager:
  ros__parameters:
  update_rate: 20 # Hz
  rover_base_control:
    type: diff_drive_controller/DiffDriveController
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/**/rover_base_control:
ros__parameters:
  type: diff_drive_controller/DiffDriveController
  use_stamped_vel: false
  use_sim_time: true
  publish_rate: 50.0
  left_wheel_names: ["Rueda_I1_link_joint", "Rueda_I2_link_joint", "Rueda_I3_link_joint"]
  right_wheel_names: ["Rueda_D1_link_joint", "Rueda_D2_link_joint", "Rueda_D3_link_joint"]
  wheel_separation: 1.90
  wheel_radius: 0.30
  # si las ruedas no se mueven bien hay que cambiar valores
  wheel_separation_multiplier: 1.0
  left_wheel_radius_multiplier: 1.0
  right_wheel_radius_multiplier: -1.0

  # Base frame_id
  base_frame_id: base_footprint
  # odom tf will be published by direct laser odometry
  enable_odom_tf: true
  # Publish limited velocity
  publish_limited_velocity: false
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 3.0
      angular:
    z:
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 3.0


/**/scara_controller:
  ros__parameters:
    joints:
      - 02_Cilindro_link_joint
      - 04_Cilindro_verti_3_link_joint
      - 07_Cilindro_verti_5_link_joint
      - 08_grip_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

/**/gripper_controller:
  ros__parameters:
    joints:
      - 09_grip_d_link_joint
      - 09_grip_i_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true