# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - 02_Cilindro_link_joint
      - 04_Cilindro_verti_3_link_joint
      - 07_Cilindro_verti_5_link_joint
      - 08_grip_link_joint
    
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true

  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - 09_grip_d_link_joint
      - 09_grip_i_link_joint

    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true